//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oneGoNclex.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public int IdBank { get; set; }
        public string Description { get; set; }
        public string BankName { get; set; }
        public string ImageBank { get; set; }
        public Nullable<int> Actif { get; set; }
    }
}
