//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oneGoNclex.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationStudent
    {
        public string RegistrationID { get; set; }
        public System.DateTime HighSchoolFrom { get; set; }
        public System.DateTime HighSchoolTo { get; set; }
        public string Diploma_Title { get; set; }
        public string Certificate_Title { get; set; }
        public string GED { get; set; }
        public string OtherDegree_Title { get; set; }
    }
}
