//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oneGoNclex.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public System.Guid id { get; set; }
        public string durationTime { get; set; }
        public string DescriptionExam { get; set; }
        public string GroupStudent { get; set; }
    }
}
