//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oneGoNclex.Infraestructure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NCLEXREVIEWEntities : DbContext
    {
        public NCLEXREVIEWEntities()
            : base("name=NCLEXREVIEWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Exam> Exams { get; set; }
        public virtual DbSet<ExplanationQuestion> ExplanationQuestions { get; set; }
        public virtual DbSet<ExternalLogin> ExternalLogins { get; set; }
        public virtual DbSet<GroupStudent> GroupStudents { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaypalPayment> PaypalPayments { get; set; }
        public virtual DbSet<Preregister> Preregisters { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Respons> Responses { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Assistence> Assistences { get; set; }
        public virtual DbSet<DocumentStudent> DocumentStudents { get; set; }
        public virtual DbSet<EducationStudent> EducationStudents { get; set; }
        public virtual DbSet<Exam_Questions> Exam_Questions { get; set; }
        public virtual DbSet<MailPayment> MailPayments { get; set; }
        public virtual DbSet<Student_Result> Student_Result { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    }
}
