//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oneGoNclex.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public System.DateTime Date { get; set; }
        public string IdStudent { get; set; }
        public decimal Amount { get; set; }
        public string Concept { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        public int ID { get; set; }
    }
}
