//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oneGoNclex.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preregister
    {
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Adress { get; set; }
        public string SocialSecurity { get; set; }
        public string PhoneNumber { get; set; }
        public string EmergencyPhone { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string Email { get; set; }
        public string EmergencyMail { get; set; }
        public string EmergencyName { get; set; }
        public string ResidenceCountry { get; set; }
        public string Gender { get; set; }
        public string HighSchool_GED { get; set; }
        public string LPNDiploma { get; set; }
        public int id { get; set; }
    }
}
