//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oneGoNclex.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public string Question1 { get; set; }
        public System.Guid id { get; set; }
        public string QuestionType { get; set; }
        public Nullable<int> Subject { get; set; }
        public string pictureQuestion { get; set; }
        public Nullable<int> BankId { get; set; }
    }
}
