//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oneGoNclex.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respons
    {
        public int id { get; set; }
        public string Response { get; set; }
        public bool Asset { get; set; }
        public System.Guid IdQ { get; set; }
    }
}
